import { openai } from "@ai-sdk/openai";
import { generateText } from "ai";
//base on your preference
const model = openai("gpt-4o-2024-11-20");

/**
 * get history of conversation from Durable Object
 */
export async function getUserConversations(
  chatDO: DurableObjectStub,
  userId: string,
  startDate: Date,
  endDate: Date
) {
  const response = await chatDO.fetch(
    `https://internal/get-messages?userId=${userId}&start=${startDate.toISOString()}&end=${endDate.toISOString()}`
  );
  
  return await response.json();
}

/**
 * analyze conversations and generate weekly summary
 */
export async function generateWeeklySummary(
  conversations: any[],
  env: Env
): Promise<string> {
  // extract and generate
  const conversationText = conversations
    .map((msg) => `${msg.role}: ${msg.content}`)
    .join("\n");

  const result = await generateText({
    model,
    system: `You are an AI assistant that analyzes user conversations and provides insightful weekly summaries.

Your task:
1. Summarize the main topics discussed this week
2. Identify patterns in user's questions or concerns
3. Provide 3-5 actionable recommendations for the user
4. Highlight any goals or tasks mentioned
5. Suggest areas for improvement or learning

Format the output in a friendly, professional email style with clear sections.`,
    prompt: `Please analyze the following conversations from this week and create a comprehensive summary with recommendations:

${conversationText}

Generate a well-structured email with:
- **Weekly Highlights**: Key topics discussed
- **Insights**: Patterns or trends observed
- **Recommendations**: 3-5 specific actionable suggestions
- **Next Steps**: Goals or tasks to focus on

Keep it concise (300-500 words) and motivating.`
  });

  return result.text;
}

/**
 * send email
 */
export async function sendWeeklySummaryEmail(
  toEmail: string,
  summaryContent: string,
  env: Env
): Promise<boolean> {
  const mailgunUrl = `https://api.mailgun.net/v3/${env.MAILGUN_DOMAIN}/messages`;

  const formData = new FormData();
  formData.append("from", `AI Assistant <${env.MAILGUN_FROM_EMAIL}>`);
  formData.append("to", toEmail);
  formData.append("subject", "🤖 Your Weekly AI Conversation Summary & Recommendations");
  formData.append("html", formatEmailHTML(summaryContent));
  formData.append("text", summaryContent);

  const response = await fetch(mailgunUrl, {
    method: "POST",
    headers: {
      Authorization: `Basic ${btoa(`api:${env.MAILGUN_API_KEY}`)}`
    },
    body: formData
  });

  if (!response.ok) {
    console.error("Failed to send email:", await response.text());
    return false;
  }

  console.log("✅ Weekly summary email sent to:", toEmail);
  return true;
}

/**
 * format email HTML
 */
function formatEmailHTML(content: string): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f5f5f5;
    }
    .container {
      background: white;
      border-radius: 8px;
      padding: 30px;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    .header {
      border-bottom: 3px solid #0066ff;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    h1 {
      color: #0066ff;
      margin: 0;
      font-size: 24px;
    }
    .content {
      white-space: pre-wrap;
      line-height: 1.8;
    }
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #eee;
      font-size: 12px;
      color: #888;
      text-align: center;
    }
    strong {
      color: #0066ff;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🤖 Your Weekly AI Summary</h1>
      <p style="color: #666; margin: 10px 0 0 0;">
        Generated on ${new Date().toLocaleDateString('en-US', { 
          weekday: 'long', 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric' 
        })}
      </p>
    </div>
    
    <div class="content">
      ${content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>')}
    </div>
    
    <div class="footer">
      <p>This summary was automatically generated by your AI Assistant.</p>
      <p>To unsubscribe or change settings, reply to this email.</p>
    </div>
  </div>
</body>
</html>
  `;
}

/**
 * main function
 */
export async function processWeeklySummaries(env: Env) {
  console.log("🔄 Starting weekly summary generation...");

  const userConfigs = await getAllUserConfigs(env);

  if (userConfigs.length === 0) {
    console.log("i No users configured for weekly summaries");
    return;
  }

  //time range -7 days
  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(startDate.getDate() - 7);

  // send summary for all user
  for (const userConfig of userConfigs) {
    try {
      console.log(`📧 Processing summary for user: ${userConfig.userId}`);

      const chatId = env.Chat.idFromName(userConfig.userId);
      const chatStub = env.Chat.get(chatId);
      const conversations = await getUserConversations(
        chatStub,
        userConfig.userId,
        startDate,
        endDate
      );

      if (!conversations || conversations.length === 0) {
        console.log(`ℹ No conversations found for user ${userConfig.userId}`);
        continue;
      }


      const summary = await generateWeeklySummary(conversations, env);

  
      await sendWeeklySummaryEmail(userConfig.email, summary, env);

      console.log(`Summary sent to ${userConfig.email}`);
    } catch (error) {
      console.error(`Error processing user ${userConfig.userId}:`, error);
    }
  }

  console.log(" Weekly summary generation completed");
}

/**
 * GET ALL USERS WHICH SET THIS BY KV
 */
async function getAllUserConfigs(env: Env): Promise<UserConfig[]> {
  // get config from KV
  const list = await env.USER_CONFIG.list();
  const configs: UserConfig[] = [];

  for (const key of list.keys) {
    const config = await env.USER_CONFIG.get(key.name, "json");
    if (config && config.email && config.enableWeeklySummary) {
      configs.push(config as UserConfig);
    }
  }

  return configs;
}

interface UserConfig {
  userId: string;
  email: string;
  enableWeeklySummary: boolean;
}